Update deployment message format in check_slack.yml and add deployment workflows for different environments

diff --git a/.github/workflows/check_slack.yml b/.github/workflows/check_slack.yml
--- a/.github/workflows/check_slack.yml
+++ b/.github/workflows/check_slack.yml
@@ -2,6 +2,9 @@ name: Deploy To Dev
 run-name: Deploy `${{ inputs.service }}` in `${{ inputs.env }}` for `${{ inputs.duration }}`
 
 on:
+  push:
+    branches:
+      - check-cache-for-python
   workflow_dispatch:
     inputs:
       env:
@@ -78,14 +81,14 @@ on:
         required: true
 
 concurrency:
-  group: deploy-${{ github.event.inputs.env }}-${{ github.event.inputs.service }}
+  group: deploy-${{ inputs.env }}-${{ inputs.service }}
 
 env:
-  ENV: ${{ github.event.inputs.env }}
+  ENV: ${{ inputs.env }}
 
 jobs:
   deploy:
-    name: '${{ github.event.inputs.env }} Deployment'
+    name: '${{ inputs.env }} Deployment'
     runs-on: ubuntu-latest
     env:
       ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
@@ -98,34 +101,50 @@ jobs:
       KUBECTL_VERSION: v1.30.0
       HELM_VERSION: v3.14.4
       GH_ACTOR: ${{ github.actor }}
-      SERVICE_NAME: ${{ github.event.inputs.service }}
-      ESTIMATED_DURATION: ${{ github.event.inputs.duration }}
-      REF: ${{ github.event.inputs.ref }}
-      OVERRIDE_SERVICE: ${{ github.event.inputs.override }}
-      ENV: ${{ github.event.inputs.env }}
+      SERVICE_NAME: ${{ inputs.service }}
+      ESTIMATED_DURATION: ${{ inputs.duration }}
+      REF: ${{ inputs.ref }}
+      OVERRIDE_SERVICE: ${{ inputs.override }}
+      ENV: ${{ inputs.env }}
 
     steps:
-      - name: Set Region Variable
-        id: set-region
+      - name: Set up Python 3.8
+        uses: actions/setup-python@v5
+        with:
+          python-version: 3.8
+
+      - name: install dependencies
         run: |
-          case "$ENV" in
-            dev-01) REGION="eu-central-1" ;;
-            dev-02) REGION="eu-west-1" ;;
-            dev-03) REGION="eu-west-3" ;;
-            qa-01) REGION="eu-south-1" ;;
-            *) echo "Invalid environment specified. Region variable not set." && exit 1 ;;
-          esac
-          echo "REGION=${REGION}" | tee -a $GITHUB_ENV
+          sudo apt-get update
+          sudo apt-get install awscli jq
+          pip install -r requirements.txt
+          pip install -r deploy/requirements.txt
+          pip install -r linenv/requirements.txt
 
-      - name: Notify Slack About Deployment
-        uses: Ilshidur/action-slack@master
-        with:
-          args: |
-            <!here> ${{ github.actor }} is taking `${{ inputs.service }}` in `${{ inputs.env }}` (_${{ env.REGION }}_) for `${{ inputs.duration }}`
+      - name: Check jq
+        run: jq -Rs '.' check_slack.yml | sed 's/\\n/\\n/g' | sed 's/\\/\\\\/g'
 
-      - name: Slack notification on success, failure, or cancellation
-        if: always()
-        uses: Ilshidur/action-slack@master
-        with:
-          args: |
-            Deployment of *${{ inputs.service }}* (ref: _${{ inputs.ref }}_) to ${{ inputs.env }} completed with status: `${{ job.status }}`
+      # - name: Set Region Variable
+      #   id: set-region
+      #   run: |
+      #     case "$ENV" in
+      #       dev-01) REGION="eu-central-1" ;;
+      #       dev-02) REGION="eu-west-1" ;;
+      #       dev-03) REGION="eu-west-3" ;;
+      #       qa-01) REGION="eu-south-1" ;;
+      #       *) echo "Invalid environment specified. Region variable not set." && exit 1 ;;
+      #     esac
+      #     echo "REGION=${REGION}" | tee -a $GITHUB_ENV
+
+      # - name: Notify Slack About Deployment
+      #   uses: Ilshidur/action-slack@master
+      #   with:
+      #     args: |
+      #       <!here> ${{ github.actor }} is taking `${{ inputs.service }}` in `${{ inputs.env }}` (_${{ env.REGION }}_) for `${{ inputs.duration }}`
+
+      # - name: Slack notification on success, failure, or cancellation
+      #   if: always()
+      #   uses: Ilshidur/action-slack@master
+      #   with:
+      #     args: |
+      #       Deployment of *${{ inputs.service }}* (ref: _${{ inputs.ref }}_) to ${{ inputs.env }} completed with status: `${{ job.status }}`
